### ISSUE TITLE
Dashboard - Implementação no relatório chamados

### ISSUE THREAD

**Issue by verdanatech-dev** [verdanatech/dashboard#1]
Implementar os seguintes filtros na tela

Filtro grupo resolvedor 2
Filtro Operação 1
Filtro Localização 1
Filtro Impacto 1

**Comment by verdanatech-marcio** [comment]
Testado, funcionando conforme pedido 
![Teste07_04](https://user-images.githubusercontent.com/80538863/113892528-76dfc180-979c-11eb-97e1-f6a780038f60.png)

**Comment by verdanatech-dev** [comment]
Analise

**Comment by verdanatech-pereira** [comment]
Obs: Filtro Operação foi ocultado por falta de definição. 
Filtros operantes são: Grupo resolvedor; Localização; Impacto
