### ISSUE TITLE
Melhoria no Relatório de SLA por Tempo de Solução

### ISSUE THREAD

**Issue by verdanatech-marcio** [verdanatech/dashboard#12]
Plugin Dashboard -> Relatórios -> Relatório SLA
Retirada de reloads no envio do relatório,
Adição dos Labels nos Inputs.
Ajuste na tabela.

**Comment by verdanatech-pereira** [comment]
Correção de filtro "todos"
![image](https://user-images.githubusercontent.com/80539522/116130738-f37e0580-a6a1-11eb-93a2-15dfae40ae8f.png)
