### ISSUE TITLE
dashboard - Menu: Relatório > Grupo por volume

### ISSUE THREAD

**Issue by verdanatech-dev** [verdanatech/dashboard#16]
Quando é clicado no valor de cada coluna não está trazendo o filtro correto 

![image](https://user-images.githubusercontent.com/48805206/116876955-a9da7100-abf3-11eb-8343-fcc92b61b8ef.png)

**Comment by verdanatech-marcio** [comment]
Testado, funcionando corretamente.
![TesteGruposPorVolume](https://user-images.githubusercontent.com/80538863/116996170-6c3c1d80-acb1-11eb-8bf8-2036ff116f18.png)
