### ISSUE TITLE
Dashboard - chamados reabertos

### ISSUE THREAD

**Issue by verdanatech-dev** [verdanatech/dashboard#17]
Relatório apresenta inconsistência 

- Chamados reabertos: São todos os chamados cujo a solução foi recusada 

![image](https://user-images.githubusercontent.com/48805206/116879076-941a7b00-abf6-11eb-88bc-2141c4c83c5d.png)

**Comment by verdanatech-marcio** [comment]
Testado, funcionando corretamente.
![TesteRelReabertos](https://user-images.githubusercontent.com/80538863/116994298-e8813180-acae-11eb-8124-21dbfc1eeb4c.png)
