### ISSUE TITLE
Dashboard - Implementação no relatório alto impacto chamados abertos / hoje

### ISSUE THREAD

**Issue by verdanatech-dev** [verdanatech/dashboard#2]
Implementar colunas do relatório

Seguintes colunar
Exibir a coluna grupo resolvedor 2
Exibir Operação 2
Ao clicar em cada linha exibir o chamado 2

**Comment by verdanatech-pereira** [comment]
Adicionado Grupo Resolvedor.
![image](https://user-images.githubusercontent.com/80539522/113906088-3c7d2100-97aa-11eb-97a8-9cb6086efc4f.png)
