### ISSUE TITLE
Verificar inconsistência 

### ISSUE THREAD

**Issue by verdanatech-dev** [verdanatech/dashboard#28]
https://github.com/verdanatech/dashboard/issues/6

![image](https://user-images.githubusercontent.com/48805206/117690220-fe03c900-b190-11eb-8147-5dca88183ecc.png)

**Comment by verdanatech-lucas** [comment]
Foi encontrado bugs na no filtro de tipo de chamado, issue já criada

**Comment by verdanatech-lucas** [comment]
Teste realizado, problema ja em progresso por marcio, após correção necessário validar

**Comment by verdanatech-marcio** [comment]
Testado, funcionado normalmente sem divergir com o GLPI
