### ISSUE TITLE
Relatório SLA - Inconsistência 

### ISSUE THREAD

**Issue by verdanatech-dev** [verdanatech/dashboard#29]
![image](https://user-images.githubusercontent.com/48805206/117690466-43c09180-b191-11eb-9ad5-708d6b4cc393.png)

**Comment by verdanatech-dev** [comment]
Apresenta inconsistência nos valores

**Comment by verdanatech-lucas** [comment]
Ainda está com inconsistência nos dados

**Comment by verdanatech-lucas** [comment]
Continua com inconsistencia, Não resolvido dentro do SLA

**Comment by verdanatech-pereira** [comment]
Mudando o tipo de status depois de uma pesquisa relatório apresenta bug
![image](https://user-images.githubusercontent.com/80539522/118161851-73240800-b3f6-11eb-94e4-73d2185104c3.png)
Testado em Homologação

**Comment by verdanatech-pereira** [comment]
Revisar filtro com grupos
![image](https://user-images.githubusercontent.com/80539522/118162371-0bba8800-b3f7-11eb-94c8-4560f92f47de.png)![image](https://user-images.githubusercontent.com/80539522/118162309-f7768b00-b3f6-11eb-99ec-85cf918670cf.png)

**Comment by verdanatech-pereira** [comment]
Tudo certo
