### ISSUE TITLE
Dashboard - Criação de Relatório em lista com volume de chamados por fila e por status.

### ISSUE THREAD

**Issue by verdanatech-dev** [verdanatech/dashboard#3]
Ao clicar na quantidade abri os chamados 2
Criação do relatório 6

Informar a regra do backlog
Qual o status do chamado a ser considerado na pesquisa?:
Cálculo: diferente de solucionado e fechado

Informar regra  do backlog DP
Significado de DP: Dentro do prazo
Qual o status do chamado a ser considerado na pesquisa?:

Informar regra  do backlog FP
Significado de FP: Fora do prazo
Qual o status do chamado a ser considerado na pesquisa?:

Informar regra chamados reabertos
Qual o status do chamado a ser considerado na pesquisa?: Quando a solução é recusada

Ao clicar no número abrir a relação de chamados

![image](https://user-images.githubusercontent.com/48805206/113763654-4f331f80-96f0-11eb-9db9-019c1d133b31.png)

**Comment by verdanatech-pereira** [comment]
Aguardando informações de BackLog, BackLog DP e BackLog FP para finalização da issue.
Link temporário para o relatório criado: /plugins/dashboard/front/reports/rel_grupos_vol.php?con=1

**Comment by verdanatech-marcio** [comment]
Testado, funcionando corretamente conforme pedido. 
![test_dash](https://user-images.githubusercontent.com/80538863/114715755-ca588f00-9d09-11eb-9537-88f8a8be7134.png)
