### ISSUE TITLE
Grupos por volume - dados inconsistentes 

### ISSUE THREAD

**Issue by verdanatech-dev** [verdanatech/dashboard#30]
![image](https://user-images.githubusercontent.com/48805206/117690862-add93680-b191-11eb-8229-c30e31e0b11b.png)

**Comment by verdanatech-dev** [comment]
Foi apresentado inconsistência nos valores apresentados

**Comment by verdanatech-lucas** [comment]
Testado, não foi encontrado nada fora do normal, necessária segunda validação

**Comment by verdanatech-marcio** [comment]
Testado funcionando corretamente, valores iguais ao GLPI.
