### ISSUE TITLE
Correção do relatório dashboard por SLA

### ISSUE THREAD

**Issue by verdanatech-lucas** [verdanatech/dashboard#33]
Tipo de chamado mesmo sendo informado no filtro, o gráfico continua trazendo informação

![image](https://user-images.githubusercontent.com/68446754/117868460-054dd400-b270-11eb-90fe-4122285356e5.png)
![image](https://user-images.githubusercontent.com/68446754/117868515-172f7700-b270-11eb-8d1e-75b79c132797.png)

**Comment by verdanatech-lucas** [comment]
Teste realizado, aparentemente sem inconsistências nos dados, e correção efetuada

**Comment by verdanatech-pereira** [comment]
Done
