### ISSUE TITLE
Ajustes Links Vazios 

### ISSUE THREAD

**Issue by verdanatech-marcio** [verdanatech/dashboard#38]
Remover Links onde o valor estiver zerado

**Comment by verdanatech-lucas** [comment]
![image](https://user-images.githubusercontent.com/68446754/119542549-0f8aca80-bd66-11eb-8e6f-e4b85c0b25b5.png)
botão ainda habilitado com o seguinte filtro

**Comment by verdanatech-lucas** [comment]
Teste realizado, problema corrigido.
