### ISSUE TITLE
Dashboard - Validar query de chamados reabertos

### ISSUE THREAD

**Issue by verdanatech-pereira** [verdanatech/dashboard#44]
Validar query de chamados reabertos

**Comment by verdanatech-marcio** [comment]
Testado funcionando normalmente, cálculo certinho!!
![image](https://user-images.githubusercontent.com/80538863/119831522-bc368a80-bed3-11eb-96f7-64a0b632743e.png)

**Comment by verdanatech-lucas** [comment]
Necessário verificar, na base de atendimento está apresentando problemas
