### ISSUE TITLE
Chamados reabertos

### ISSUE THREAD

**Issue by verdanatech-dev** [verdanatech/dashboard#48]
Está exibindo chamados que não são reabertos

![image](https://user-images.githubusercontent.com/48805206/120222638-a21fe380-c216-11eb-85b9-d278a21d01d9.png)

**Comment by verdanatech-marcio** [comment]
Testado, funcionando corretamente!!
![image](https://user-images.githubusercontent.com/80538863/120382578-2f883400-c2fa-11eb-9586-a9075f8b8f6a.png)
![image](https://user-images.githubusercontent.com/80538863/120382637-4169d700-c2fa-11eb-92e5-666f219667a9.png)
