### ISSUE TITLE
Dashboard - Criar relatório de chamados reabertos

### ISSUE THREAD

**Issue by verdanatech-dev** [verdanatech/dashboard#5]
Filtro Período 1
Filtro Tipo (Incidente/Requisição 1
Filtro Grupo Técnico Resolvedor 1
Filtro impacto 1
Exportação CSV 1
Desenvolvimento do relatório 6

![image](https://user-images.githubusercontent.com/48805206/113764074-dbdddd80-96f0-11eb-880d-08ffd0c18e96.png)

**Comment by verdanatech-marcio** [comment]
Testado, funcionando corretamente conforme pedido. 
![test_dash](https://user-images.githubusercontent.com/80538863/114715464-777ed780-9d09-11eb-836f-7a9d23167e20.png)
