### ISSUE TITLE
Implementação da label (Total de chamados)

### ISSUE THREAD

**Issue by verdanatech-dev** [verdanatech/dashboard#50]
Implementar no menu: Relatório > Relatório SLA

Implementar o total de chamados 

![image](https://user-images.githubusercontent.com/48805206/120224569-1740e800-c21a-11eb-8a4c-4ab8ba053cc1.png)

**Comment by verdanatech-lucas** [comment]
O total de chamados pelo teste realizado, está batendo com a label
