### ISSUE TITLE
Correção de interface 

### ISSUE THREAD

**Issue by verdanatech-dev** [verdanatech/dashboard#52]
layout não está exibindo os botoes apos consultar data 
![image](https://user-images.githubusercontent.com/48805206/123638994-26558e80-d7f6-11eb-92bb-5ef0b4bc9b24.png)

**Comment by verdanatech-marcio** [comment]
Testado,os botões não sobrepostos mais.
![image](https://user-images.githubusercontent.com/80538863/124768963-78419700-df0f-11eb-8b99-d2885b442790.png)
