### ISSUE TITLE
Atualização dos cards

### ISSUE THREAD

**Issue by verdanatech-dev** [verdanatech/dashboard#53]
Examplo para o novo card

![image](https://user-images.githubusercontent.com/48805206/127221294-42a672c9-4436-4734-824f-ee1d99b98905.png)

Calculo de porcentagem

Total de chamados dentro do praso * 100 / total  de chamados

**Comment by verdanatech-pereira** [comment]
Dados consistência e interface do gráfico alterado. 
![image](https://user-images.githubusercontent.com/80539522/128175428-fb2b5d62-fb1c-4264-b2bb-cb5cf358af17.png)
![image](https://user-images.githubusercontent.com/80539522/128175466-d833d19d-fe0f-4a17-89be-c12fe8019d66.png)
