### ISSUE TITLE
Melhoria Visual no Dashboard por SLA 

### ISSUE THREAD

**Issue by verdanatech-marcio** [verdanatech/dashboard#54]
## MELHORIAS
Retirar Total de Chamados Dentro do Prazo
Alinhar Gráficos 
Retirar Espaço Entre o Gráfico e Porcentagem
Verificar a possibilidade de Mudança das Cores

para cada grafico deve ser adicionado uma cor a partir da meta e da regra

## META

- Muito alto: 95%
- Alto: 95%
- Médio: 70%
- Baixo: 90%
- Requisição e incidente: 85%

## REGRA
>= meta = verde
>= meta-5 p,p e < meta (nesse exemplo entre >= 90% e < 95%) = Amarelo
< meta % = Vermelho

**Comment by verdanatech-luana** [comment]
Teste executado, atendendo todos os requisitos.

 
![2021-08-05_14-15](https://user-images.githubusercontent.com/86842154/128393105-5ad768d7-e49a-43e5-91d9-525b353f54c3.png)

**Comment by verdanatech-pereira** [comment]
Verificado, cores alterando de acordo com porcentagem!
