### ISSUE TITLE
Dashboard - Desenvolvimento do dashboard enviado na planilha

### ISSUE THREAD

**Issue by verdanatech-dev** [verdanatech/dashboard#6]
Implementar filtro de datas (data inicial data final ) 1
Implementar filtro do tipo de chamado (Incidente e requisição) 1
Implementar filtro do Impacto do chamado 1
Implementar filtro de grupo resolvedor (Permitir seleção) 2
6 gráficos (Pendente levantamento das informações) 18
Cada gráfico ao ser clicado deve abrir a tela de chamados, aplicando
o filtro do gráfico 6

![image](https://user-images.githubusercontent.com/48805206/113764408-47c04600-96f1-11eb-82ab-6408879bc87d.png)

**Comment by verdanatech-pereira** [comment]
Ajustes de layout finalizado
![image](https://user-images.githubusercontent.com/80539522/115240021-b8a22d80-a0f5-11eb-8880-3c558b2ab7fa.png)

**Comment by verdanatech-marcio** [comment]
Testado, funcionando corretamente, layout ajustado ficou bem melhor.
![teste_new_Dash](https://user-images.githubusercontent.com/80538863/115240391-16367a00-a0f6-11eb-8a13-977336118900.png)

**Comment by verdanatech-dev** [comment]
![image](https://user-images.githubusercontent.com/48805206/115288862-57478200-a128-11eb-9616-9729b8b44a97.png)

**Comment by verdanatech-dev** [comment]
Problema de usabilidade 

Adicionar as label em cada input

Quando o usuário preenche um campo e clica em pesquisar, ele mostra uma mensagem que outro campo precisa ser preenchido e limpa os outros campos .
