### ISSUE TITLE
Alterar os 4 primeiros gráficos para Incidente 

### ISSUE THREAD

**Issue by verdanatech-marcio** [verdanatech/dashboard#61]
Mudar Querys, quando o filtro de Tipo de Chamado for Todos deve trazer apenas incidentes 
Caso opte por Requisção buscar apenas requisição.
Formatar Data no Padrão BR

**Comment by verdanatech-lucas** [comment]
Implementação finalizada, os 4 primeiros gráficos foram alterados para retornar incidentes quando selecionado o filtro TODOS

**Comment by verdanatech-dev** [comment]
O filtro não esta trazendo apenas os incidentes para quando selecionados todos os tipos
![image](https://user-images.githubusercontent.com/48805206/129265353-972ceeee-14e6-4232-aa29-f78493c6fa0b.png)

**Comment by verdanatech-dev** [comment]
Não foi aplicado a formatação dos datas

![image](https://user-images.githubusercontent.com/48805206/129265791-7d6829ca-78dd-4956-8aab-4f9f3a6422f5.png)

**Comment by verdanatech-lucas** [comment]
Correção do link para quando não temos grupo resolvedor no campo, formatação da data inicial e final para padrão brasileiro

**Comment by verdanatech-luana** [comment]
Teste executado, data formatada para BR, os gráficos apresentam o impacto dos chamados de Incidentes quando filtrar para Todos e apenas Requisição quando filtrado para o mesmo.

![2021-08-13_10-45](https://user-images.githubusercontent.com/86842154/129374092-6bb79544-95f2-4582-8cab-363f98f3e1f0.png)

![2021-08-13_11-09](https://user-images.githubusercontent.com/86842154/129374119-162fd721-e7e8-4ca2-8441-b06583bf47c7.png)

![2021-08-13_11-12](https://user-images.githubusercontent.com/86842154/129374136-55dee6c4-55b4-43a6-b63b-938883f8eb0c.png)

**Comment by verdanatech-marcio** [comment]
Testado, funcionando corretamente.
Data Formatada BR
Gráficos Trazendo Só Incidentes
![TesteDash](https://user-images.githubusercontent.com/80538863/129730482-18ef61d0-afce-469d-935c-5e0ebd73013f.png)
