### ISSUE TITLE
Adicionar branch 9.5 e 9.5 - dev

### ISSUE THREAD

**Issue by verdanatech-luana** [verdanatech/dashboard#62]
![2021-08-16_11-32](https://user-images.githubusercontent.com/86842154/129580888-9e5c220f-d6ce-46bc-9a97-c9280b6da39f.png)

![2021-08-16_11-34](https://user-images.githubusercontent.com/86842154/129580904-f2a7e13f-9379-4227-b182-ff031227b998.png)

**Comment by verdanatech-luana** [comment]
Branch 9.5 e 9.5-dev criadas 

![2021-08-16_12-28](https://user-images.githubusercontent.com/86842154/129589299-99416b01-56a7-4030-bf0c-bf8492bfe09f.png)

![2021-08-16_12-30](https://user-images.githubusercontent.com/86842154/129589328-900083b0-899a-41ea-a07d-c6fe567920f1.png)

**Comment by verdanatech-marcio** [comment]
Testado, funcionando corretamente no GLPI - 9.5
![TesteDash](https://user-images.githubusercontent.com/80538863/129726552-5aa6f957-e6ec-475b-841e-c3bbcccf3f9f.png)
