### ISSUE TITLE
Alterar Filtro Query Relatórios por Técnicos

### ISSUE THREAD

**Issue by verdanatech-marcio** [verdanatech/dashboard#64]
Alterar filtro de chamados fechados, pois estava dando divergência de valores
GLPI 9.4 -> Plugin Dashboard -> Relatórios -> Relatório Por Técnicos 
Divergência de Valores Entre Relatório e o GLPI

**Comment by verdanatech-luana** [comment]
Número de chamados de acordo.
![2021-09-03_10-20](https://user-images.githubusercontent.com/86842154/132012291-d35d0696-e6f0-44ab-9024-e2e206f7493c.png)

![2021-09-03_10-21](https://user-images.githubusercontent.com/86842154/132012325-fe7cdb60-efc6-4735-8032-fa5ea68f9632.png)

![2021-09-03_10-22](https://user-images.githubusercontent.com/86842154/132012341-7ab2a1b7-5a60-4415-96c2-40dd03a75035.png)

![2021-09-03_10-22_1](https://user-images.githubusercontent.com/86842154/132012361-70def879-7e82-42f7-8fe4-359b97325b7b.png)

![2021-09-03_10-22_2](https://user-images.githubusercontent.com/86842154/132012406-7b3e2eea-9d2f-47c1-a08e-4e7b0bf7eb7e.png)

![2021-09-03_10-22_3](https://user-images.githubusercontent.com/86842154/132012439-0228b587-2af4-4d89-b34c-8e8351931b68.png)

![2021-09-03_10-23](https://user-images.githubusercontent.com/86842154/132012463-7744d618-57de-4c42-81aa-1914604b2406.png)
