### ISSUE TITLE
Dashboard - Correção de layout | Relatório > Chamados Reabertos; Chamados por Grupo Volume

### ISSUE THREAD

**Issue by verdanatech-pereira** [verdanatech/dashboard#8]
Letras estão ilegíveis
![image](https://user-images.githubusercontent.com/80539522/114865462-a445f400-9dc8-11eb-869c-c7539047d763.png)

**Comment by verdanatech-marcio** [comment]
Testado, bug corrigido.
![teste_new_Dash](https://user-images.githubusercontent.com/80538863/115256801-eee7a900-a105-11eb-843f-349b53f911b7.png)
